<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Add Item To Candy Items Table</title>
</head>
<body>
	<form action="addItemToTable.phtml" method="POST">
		<h1>Add New Item to CandyItems Table</h1>
		<hr>
        <p>Enter the following details</p>
		<label>Candy Name</label>
		<input type="text" name="candyName" required>
		<br>
        <label>Candy Type: </label>
		<input type="text" name="candyType" required>
		<br>
         <label>Price of Candy: </label>
		<input type="number" name="candyPrice" step=".01"required>
		<br><br>
		<button type="submit" id="submit">Add New Item</button>
	</form>
</body>
</html>