<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Login | Constructor example</title>

    <style>
        img{
            width: 100%;
            height:100%;
        }
    </style>
</head>

<body>
    <form action="login.php" method="POST" name="form">
        <h1>LOGIN</h1>
        <hr>
        <br>
        <label>Username: </label>
        <input type="text" name="username">
        <br>
        <br>
        <label>Password: </label>
        <input type="password" name="password">
        <br>
        <br>
        <button type="submit" id="login">Login</button>
    </form>
</body>

</html>

 <?php
        // $retrieved_username = $_POST['username'];
        // $retrieved_password = $_POST['password'];

        // class UserNameAndPassword {
        //     private $username;
        //     private $password;
 
        //     function __construct() {
        //         $this->username = $_POST['username'];
        //         $this->password = $_POST['password'];

        //         if (strlen($this->username) <= 0 || strlen($this->password) <= 0) {
        //             echo "<br>One or both inputs were not filled!";
        //             return false;
        //         } else{
        //             echo "<br>You entered " . $this->username . " as your username. <br>You entered " . $this->password . " as your password. <br>";
        //             return true;
        //         }
        //     }

        //     Public function __destruct() {
        //         // echo "destruct invoked!!";
                
        //     }
        // }

        // $b = new UserNameAndPassword();



        // // $retrieved_username = $_POST['username'];
        // // $retrieved_password = $_POST['password'];

        // class UserNameAndPassword {
        //     private $username;
        //     private $password;
 
        //     function __construct($username, $password) {
        //         $this->username = $username;
        //         $this->password = $password;

        //         if (strlen($username) <= 0 || strlen($password) <= 0) {
        //             echo "<br>One or both inputs were not filled!";
        //             return false;
        //         } else{
        //             echo "<br>You entered " . $this->username . " as your username. <br>You entered " . $this->password . " as your password. <br>";
        //             return true;
        //         }
        //     }

        //     Public function __destruct() {
        //         // echo "destruct invoked!!";
                
        //     }
        // }

        // $b = new UserNameAndPassword($retrieved_username, $retrieved_password);

    ?>